// songActions.ts
export const GET_SONGS = 'GET_SONGS';
export const ADD_SONG = 'ADD_SONG';
export const DELETE_SONG = 'DELETE_SONG';
export const UPDATE_SONG = 'UPDATE_SONG';
export const PLAY_CURRENT = 'PLAY_CURRENT';
export const SINGLE = 'SINGLE';
export const ADD_ERROR = 'ADD_ERROR';
export const SEARCH_SONGS_REQUEST = 'SEARCH_SONGS_REQUEST';
export const SEARCH_SONGS_SUCCESS = 'SEARCH_SONGS_SUCCESS';
export const SEARCH_SONGS_FAILURE = 'SEARCH_SONGS_FAILURE';
export const TOTAL_COUNT_SONGS='TOTAL_COUNT_SONGS';
export const TOTAL_SONGS_BY_GENRE='TOTAL_SONGS_BY_GENRE'
export const TOTAL_SONGS_BY_ARTISTANDALBUMS='TOTAL_SONGS_BY_ARTISTANDALBUMS';
export const TOTAL_SONGS_IN_ALBUM='TOTAL_SONGS_IN_ALBUM';